application: heroic-footing-93601
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /.*
  script: comments.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
